trigger:
  branches:
    include:
      - "*"
  paths:
    include:
      - "load-tests/**"
      - ".azuredevops/pipelines/alt-load-tests.yml"

pr:
  branches:
    include:
      - "*"
  paths:
    include:
      - "load-tests/**"
      - ".azuredevops/pipelines/alt-load-tests.yml"

pool:
  vmImage: ubuntu-latest
variables:
  serviceConnection: svc_CSA_sub
  loadTestResource: lt-aistock-dev-003
  loadTestResourceGroup: rg-aistock-dev-003

stages:
  - stage: LoadTest
    displayName: Load Test
    jobs:
      - job: LoadTest
        displayName: Load Test
        pool:
          vmImage: ubuntu-latest
        steps:
          - script: |
              echo "Preparing load test files"
              mkdir -p $(System.DefaultWorkingDirectory)/.azuredevops/pipelines/load-tests || true
              cp -v $(System.DefaultWorkingDirectory)/load-tests/paths.csv $(System.DefaultWorkingDirectory)/.azuredevops/pipelines/load-tests/paths.csv || true
            displayName: 'Pre-step: copy load-tests files to pipeline path'

          - task: AzureLoadTest@1
            inputs:
              azureSubscription: svc_CSA_sub
              loadTestConfigFile: .azuredevops/pipelines/alt-config.yml
              resourceGroup: rg-aistock-dev-003
              loadTestResource: lt-aistock-dev-003

          - publish: $(System.DefaultWorkingDirectory)/loadTest
            artifact: results
