version: v0.1
testId: ecca431f-35fd-4040-9be0-605062de0501
testPlan: test-plan.azure.jmx
testType: JMX
engineInstances: 1
publicIPDisabled: false
splitAllCSVs: false
displayName: Test - 08/22/2025 05:08:29 PM
description: JMeter load test
configurationFiles:
  - ../../load-tests/paths.csv
autoStop:
  errorPercentage: 90
  timeWindow: 60
env:
  - name: loop
    value:
  - name: threads
    value:
  - name: ramp
    value:
  - name: host
    value: app-aistock-dev-003.azurewebsites.net
  - name: port
    value: 443
  - name: protocol
    value: https
  - name: path
    value:
  - name: debugCsv
    value:
  - name: pathsCsv
    value:
referenceIdentities:
  - kind: KeyVault
    type: SystemAssigned
  - kind: Metrics
    type: SystemAssigned
appComponents:
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.web/serverfarms/asp-aistock-dev-003
    resourceName: asp-aistock-dev-003
    kind: linux
    metrics:
      - name: CpuPercentage
        aggregation: Average
        namespace: microsoft.web/serverfarms
      - name: MemoryPercentage
        aggregation: Average
        namespace: microsoft.web/serverfarms
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.keyvault/vaults/kv-aistock-dev-003
    resourceName: kv-aistock-dev-003
    metrics:
      - name: Availability
        aggregation: Average
        namespace: microsoft.keyvault/vaults
      - name: ServiceApiHit
        aggregation: Count
        namespace: microsoft.keyvault/vaults
      - name: ServiceApiLatency
        aggregation: Average
        namespace: microsoft.keyvault/vaults
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.insights/components/appi-aistock-dev-003
    resourceName: appi-aistock-dev-003
    kind: web
    metrics:
      - name: requests/duration
        aggregation: Average
        namespace: microsoft.insights/components
      - name: requests/failed
        aggregation: Count
        namespace: microsoft.insights/components
      - name: requests/count
        aggregation: Count
        namespace: microsoft.insights/components
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.sql/servers/sql-aistock-dev-003/databases/sqldb-aistock-dev-003
    resourceName: sql-aistock-dev-003/sqldb-aistock-dev-003
    kind: v12.0,user
    metrics:
      - name: cpu_percent
        aggregation: Total
        namespace: microsoft.sql/servers/databases
      - name: connection_failed
        aggregation: Maximum
        namespace: microsoft.sql/servers/databases
      - name: deadlock
        aggregation: Total
        namespace: microsoft.sql/servers/databases
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.web/sites/app-aistock-dev-003
    resourceName: app-aistock-dev-003
    kind: app,linux,container
    metrics:
      - name: Http5xx
        aggregation: Total
        namespace: microsoft.web/sites
      - name: Requests
        aggregation: Total
        namespace: microsoft.web/sites
      - name: HttpResponseTime
        aggregation: Average
        namespace: microsoft.web/sites
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.web/sites/api-aistock-dev-003
    resourceName: api-aistock-dev-003
    kind: app,linux,container
    metrics:
      - name: Http5xx
        aggregation: Total
        namespace: microsoft.web/sites
      - name: Requests
        aggregation: Total
        namespace: microsoft.web/sites
      - name: HttpResponseTime
        aggregation: Average
        namespace: microsoft.web/sites
  - resourceId: /subscriptions/64c3d212-40ed-4c6d-a825-6adfbdf25dad/resourcegroups/rg-aistock-dev-003/providers/microsoft.sql/servers/sql-aistock-dev-003/databases/master
    resourceName: sql-aistock-dev-003/master
    kind: v12.0,system
    metrics:
      - name: cpu_percent
        aggregation: Total
        namespace: microsoft.sql/servers/databases
      - name: connection_failed
        aggregation: Maximum
        namespace: microsoft.sql/servers/databases
      - name: deadlock
        aggregation: Total
        namespace: microsoft.sql/servers/databases
