# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureTestPlan@0
  inputs:
    azureSubscription: 'svc_CSA_sub'
    testSelector: 'automatedTests'
    testPlanOrRunSelector: 'testPlan'
    testPlan: '1427'
    testSuite: '1429'
    testConfiguration: '72'
    testLanguageInput: 'Python'