services:
  aistocktradeapp:
    image: ${DOCKER_REGISTRY-}aistocktradeapp
    build:
      context: .
      dockerfile: AiStockTradeApp/Dockerfile
    networks:
      - app-network

  AiStockTradeAppApi:
    image: ${DOCKER_REGISTRY-}aistocktradeapp-api:latest
    build:
      context: .
      dockerfile: AiStockTradeApp.Api/Dockerfile
    ports:
      - "8082:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=StockTraderDb;User Id=sa;Password=YourStrong@Passw0rd;TrustServerCertificate=true;MultipleActiveResultSets=true"
      USE_INMEMORY_DB: "false"
    depends_on:
      sqlserver:
        condition: service_healthy
    networks:
      app-network:
        aliases:
          - AiStockTradeAppApi
          - aistocktradeappapi

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong@Passw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P $${SA_PASSWORD} -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - app-network

volumes:
  sqlserver_data:

networks:
  app-network:
    driver: bridge
