name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "9.0.x"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test
    name: Build and Push Container
    outputs:
      container-image: ${{ steps.image.outputs.image }}
      container-image-backup: ${{ steps.verify.outputs.final-image }}
      test-output: ${{ steps.verify.outputs.test-output }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set container registry name
        id: registry
        run: |
          # Set the registry name based on branch/environment
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "registry_name=aistocktrackerprod" >> $GITHUB_OUTPUT
          else
            echo "registry_name=aistocktrackerdev" >> $GITHUB_OUTPUT
          fi

      - name: Debug Environment Variables
        run: |
          echo "Available environment variables:"
          echo "Registry name: ${{ steps.registry.outputs.registry_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "ACR_USERNAME available: ${{ secrets.ACR_USERNAME != '' }}"
          echo "ACR_PASSWORD available: ${{ secrets.ACR_PASSWORD != '' }}"

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry.outputs.registry_name }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Verify Docker login
        run: |
          echo "Docker login successful"
          echo "Registry: ${{ steps.registry.outputs.registry_name }}.azurecr.io"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.registry.outputs.registry_name }}.azurecr.io/ai-stock-trade-app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Set image output
        id: image
        run: |
          echo "=== METADATA DEBUG ==="
          echo "Meta step outputs:"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "Version: ${{ steps.meta.outputs.version }}"
          echo "JSON: ${{ steps.meta.outputs.json }}"
          
          echo "=== PROCESSING TAGS ==="
          echo "Available tags:"
          echo "${{ steps.meta.outputs.tags }}"
          
          # Store tags in variable for processing
          TAGS="${{ steps.meta.outputs.tags }}"
          echo "TAGS variable: ${TAGS}"
          
          # Prefer SHA tag for deployment, fallback to first tag
          SHA_TAG=$(echo "${TAGS}" | grep "sha-" | head -1 || echo "")
          echo "SHA_TAG found: ${SHA_TAG}"
          
          if [ -n "$SHA_TAG" ]; then
            echo "Using SHA tag: ${SHA_TAG}"
            echo "image=${SHA_TAG}" >> $GITHUB_OUTPUT
            echo "DEBUG: Set output to ${SHA_TAG}"
          else
            FIRST_TAG=$(echo "${TAGS}" | head -1)
            echo "Using first tag: ${FIRST_TAG}"
            echo "image=${FIRST_TAG}" >> $GITHUB_OUTPUT
            echo "DEBUG: Set output to ${FIRST_TAG}"
          fi
          
          echo "=== VERIFY OUTPUT SETTING ==="
          echo "Image output should be set to: $(if [ -n '$SHA_TAG' ]; then echo '$SHA_TAG'; else echo '$FIRST_TAG'; fi)"
          
      - name: Verify output and set job output
        id: verify
        run: |
          echo "=== BUILD JOB OUTPUT VERIFICATION ==="
          echo "Step image ID: image"
          echo "Step output: ${{ steps.image.outputs.image }}"
          echo "Job outputs will be:"
          echo "container-image: ${{ steps.image.outputs.image }}"
          echo "=== DEBUG: All step outputs ==="
          echo "Meta outputs tags: ${{ steps.meta.outputs.tags }}"
          echo "Image step outputs: ${{ toJson(steps.image.outputs) }}"
          # Also set the output from this step for debugging
          echo "final-image=${{ steps.image.outputs.image }}" >> $GITHUB_OUTPUT
          echo "=== TESTING OUTPUT SETTING ==="
          echo "test-output=hello-world" >> $GITHUB_OUTPUT
          echo "Should see test-output in job outputs"
          
      - name: Final output verification
        run: |
          echo "=== FINAL VERIFICATION ==="
          echo "Image output: ${{ steps.image.outputs.image }}"
          echo "Verify output: ${{ steps.verify.outputs.final-image }}"
          echo "Test output: ${{ steps.verify.outputs.test-output }}"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Development
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    environment: development

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-ai-stock-tracker-dev
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/parameters.dev.json containerImage=${{ needs.build.outputs.container-image }} alphaVantageApiKey=${{ secrets.ALPHA_VANTAGE_API_KEY }} twelveDataApiKey=${{ secrets.TWELVE_DATA_API_KEY }}
          failOnStdErr: false

      - name: Update Web App Container
        run: |
          echo "Container Image: ${{ needs.build.outputs.container-image }}"
          if [ -z "${{ needs.build.outputs.container-image }}" ]; then
            echo "ERROR: Container image is empty!"
            exit 1
          fi
          az webapp config container set \
            --name ai-stock-tracker-dev-webapp \
            --resource-group rg-ai-stock-tracker-dev \
            --container-image-name "${{ needs.build.outputs.container-image }}" \
            --container-registry-url "https://${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io" \
            --container-registry-user "${{ secrets.REGISTRY_USERNAME }}" \
            --container-registry-password "${{ secrets.REGISTRY_PASSWORD }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Debug Variables
        run: |
          echo "=== DEPLOYMENT DEBUG INFO ==="
          echo "Job name: deploy-prod"
          echo "GitHub ref: ${{ github.ref }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Environment input: ${{ github.event.inputs.environment }}"
          echo "=== BUILD JOB OUTPUTS ==="
          echo "Build job result: ${{ needs.build.result }}"
          echo "Build job outputs: ${{ toJson(needs.build.outputs) }}"
          echo "Container image from needs: ${{ needs.build.outputs.container-image }}"
          echo "Container image backup: ${{ needs.build.outputs.container-image-backup }}"
          echo "Test output: ${{ needs.build.outputs.test-output }}"
          echo "=== VARIABLES ==="
          echo "Resource Group: ${{ vars.AZURE_RESOURCE_GROUP_PROD }}"
          echo "Subscription ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "Container Image: ${{ needs.build.outputs.container-image }}"

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-ai-stock-tracker-prod
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/parameters.prod.json containerImage=${{ needs.build.outputs.container-image }} alphaVantageApiKey=${{ secrets.ALPHA_VANTAGE_API_KEY }} twelveDataApiKey=${{ secrets.TWELVE_DATA_API_KEY }}
          failOnStdErr: false

      - name: Update Web App Container
        run: |
          echo "Container Image: ${{ needs.build.outputs.container-image }}"
          if [ -z "${{ needs.build.outputs.container-image }}" ]; then
            echo "ERROR: Container image is empty!"
            exit 1
          fi
          az webapp config container set \
            --name ai-stock-tracker-prod-webapp \
            --resource-group rg-ai-stock-tracker-prod \
            --container-image-name "${{ needs.build.outputs.container-image }}" \
            --container-registry-url "https://${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io" \
            --container-registry-user "${{ secrets.REGISTRY_USERNAME }}" \
            --container-registry-password "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Run Health Check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          curl -f https://ai-stock-tracker-prod-webapp.azurewebsites.net/health || exit 1
          echo "Health check passed!"

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    name: Security Scan
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.container-image }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
