name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - prod

env:
  AZURE_WEBAPP_PACKAGE_PATH: "."
  DOTNET_VERSION: "9.0.x"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test Application

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore

      - name: Build application
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

  build:
    runs-on: ubuntu-latest
    needs: test
    name: Build and Push Container
    outputs:
      container-image: ${{ steps.extract-image.outputs.image }}
      test-output: ${{ steps.extract-image.outputs.test-output }}
      meta-tags: ${{ steps.meta.outputs.tags }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set container registry name
        id: registry
        run: |
          # Set the registry name based on branch/environment
          if [[ "${{ github.ref }}" == "refs/heads/main" ]] || [[ "${{ github.event.inputs.environment }}" == "prod" ]]; then
            echo "registry_name=aistocktrackerprod" >> $GITHUB_OUTPUT
          else
            echo "registry_name=aistocktrackerdev" >> $GITHUB_OUTPUT
          fi

      - name: Debug Environment Variables
        run: |
          echo "Available environment variables:"
          echo "Registry name: ${{ steps.registry.outputs.registry_name }}"
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "ACR_USERNAME available: ${{ secrets.ACR_USERNAME != '' }}"
          echo "ACR_PASSWORD available: ${{ secrets.ACR_PASSWORD != '' }}"

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ steps.registry.outputs.registry_name }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Verify Docker login
        run: |
          echo "Docker login successful"
          echo "Registry: ${{ steps.registry.outputs.registry_name }}.azurecr.io"

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ steps.registry.outputs.registry_name }}.azurecr.io/ai-stock-trade-app
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix=sha-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Debug metadata outputs
        run: |
          echo "=== METADATA STEP DEBUG ==="
          echo "Meta step ID: meta"
          echo "Meta outputs (JSON): ${{ toJson(steps.meta.outputs) }}"
          echo "Meta tags raw:"
          echo '${{ steps.meta.outputs.tags }}'
          echo "Meta version: '${{ steps.meta.outputs.version }}'"
          echo "=== END METADATA DEBUG ==="

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Extract container image for deployment
        id: extract-image
        run: |
          echo "=== EXTRACTING DEPLOYMENT IMAGE ==="
          
          # Get tags from metadata step using heredoc to preserve newlines
          TAGS=$(cat << 'EOFTAGS'
          ${{ steps.meta.outputs.tags }}
          EOFTAGS
          )
          
          echo "Available tags from metadata:"
          echo "${TAGS}"
          echo "Number of tags: $(echo "${TAGS}" | wc -l)"
          
          # Check if TAGS is empty
          if [ -z "${TAGS}" ]; then
            echo "ERROR: No tags received from metadata step!"
            echo "Meta step outputs: ${{ toJson(steps.meta.outputs) }}"
            exit 1
          fi
          
          # Find SHA tag (preferred for deployment) - handle multiline properly
          SHA_TAG=$(echo "${TAGS}" | grep -E "sha-[a-f0-9]+" | head -1 | tr -d '\n\r')
          echo "SHA_TAG search result: '${SHA_TAG}'"
          
          if [ -n "${SHA_TAG}" ]; then
            echo "Found SHA tag: ${SHA_TAG}"
            DEPLOY_IMAGE="${SHA_TAG}"
          else
            # Fallback to first tag - strip whitespace and newlines
            DEPLOY_IMAGE=$(echo "${TAGS}" | head -1 | tr -d '\n\r' | xargs)
            echo "Using first tag: ${DEPLOY_IMAGE}"
          fi
          
          echo "=== SETTING OUTPUTS ==="
          echo "Deployment image: '${DEPLOY_IMAGE}'"
          echo "DEPLOY_IMAGE length: ${#DEPLOY_IMAGE}"
          
          # Check if DEPLOY_IMAGE is empty
          if [ -z "${DEPLOY_IMAGE}" ]; then
            echo "ERROR: DEPLOY_IMAGE is empty!"
            exit 1
          fi
          
          # Set outputs with explicit formatting
          echo "image=${DEPLOY_IMAGE}" >> "$GITHUB_OUTPUT"
          echo "test-output=hello-world" >> "$GITHUB_OUTPUT"
          
          echo "=== VERIFICATION ==="
          echo "GITHUB_OUTPUT contents:"
          cat "$GITHUB_OUTPUT"
          echo "=== END GITHUB_OUTPUT ==="
          
      - name: Test immediate output reading
        run: |
          echo "=== IMMEDIATE OUTPUT TEST ==="
          echo "Can we read the image output immediately?"
          echo "Image output from previous step: ${{ steps.extract-image.outputs.image }}"
          echo "Test output from previous step: ${{ steps.extract-image.outputs.test-output }}"
          echo "Meta tags: ${{ steps.meta.outputs.tags }}"
          
      - name: Final output verification
        run: |
          echo "=== FINAL VERIFICATION ==="
          echo "Container image: ${{ steps.extract-image.outputs.image }}"
          echo "Test output: ${{ steps.extract-image.outputs.test-output }}"
          echo "Meta tags: ${{ steps.meta.outputs.tags }}"
          echo "=== JOB OUTPUTS WILL BE ==="
          echo "container-image: ${{ steps.extract-image.outputs.image }}"
          echo "test-output: ${{ steps.extract-image.outputs.test-output }}"
          echo "meta-tags: ${{ steps.meta.outputs.tags }}"

  deploy-dev:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Development
    if: github.ref == 'refs/heads/develop' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'dev')
    environment: development

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-ai-stock-tracker-dev
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/parameters.dev.json containerImage=${{ needs.build.outputs.container-image }} alphaVantageApiKey=${{ secrets.ALPHA_VANTAGE_API_KEY }} twelveDataApiKey=${{ secrets.TWELVE_DATA_API_KEY }}
          failOnStdErr: false

      - name: Update Web App Container
        run: |
          echo "Container Image: ${{ needs.build.outputs.container-image }}"
          if [ -z "${{ needs.build.outputs.container-image }}" ]; then
            echo "ERROR: Container image is empty!"
            exit 1
          fi
          az webapp config container set \
            --name ai-stock-tracker-dev-webapp \
            --resource-group rg-ai-stock-tracker-dev \
            --container-image-name "${{ needs.build.outputs.container-image }}" \
            --container-registry-url "https://${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io" \
            --container-registry-user "${{ secrets.REGISTRY_USERNAME }}" \
            --container-registry-password "${{ secrets.REGISTRY_PASSWORD }}"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Production
    if: github.ref == 'refs/heads/main' || (github.event_name == 'workflow_dispatch' && github.event.inputs.environment == 'prod')
    environment: production

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Debug Variables
        run: |
          echo "=== DEPLOYMENT DEBUG INFO ==="
          echo "Job name: deploy-prod"
          echo "GitHub ref: ${{ github.ref }}"
          echo "Event name: ${{ github.event_name }}"
          echo "Environment input: ${{ github.event.inputs.environment }}"
          echo "=== BUILD JOB OUTPUTS ==="
          echo "Build job result: ${{ needs.build.result }}"
          echo "Build job outputs: ${{ toJson(needs.build.outputs) }}"
          echo "Container image from needs: ${{ needs.build.outputs.container-image }}"
          echo "Test output: ${{ needs.build.outputs.test-output }}"
          echo "Meta tags: ${{ needs.build.outputs.meta-tags }}"
          echo "=== VARIABLES ==="
          echo "Resource Group: ${{ vars.AZURE_RESOURCE_GROUP_PROD }}"
          echo "Subscription ID: ${{ vars.AZURE_SUBSCRIPTION_ID }}"
          echo "Container Image: ${{ needs.build.outputs.container-image }}"

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ vars.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: rg-ai-stock-tracker-prod
          template: ./infrastructure/main.bicep
          parameters: ./infrastructure/parameters.prod.json containerImage=${{ needs.build.outputs.container-image }} alphaVantageApiKey=${{ secrets.ALPHA_VANTAGE_API_KEY }} twelveDataApiKey=${{ secrets.TWELVE_DATA_API_KEY }}
          failOnStdErr: false

      - name: Update Web App Container
        run: |
          echo "Container Image: ${{ needs.build.outputs.container-image }}"
          if [ -z "${{ needs.build.outputs.container-image }}" ]; then
            echo "ERROR: Container image is empty!"
            exit 1
          fi
          az webapp config container set \
            --name ai-stock-tracker-prod-webapp \
            --resource-group rg-ai-stock-tracker-prod \
            --container-image-name "${{ needs.build.outputs.container-image }}" \
            --container-registry-url "https://${{ vars.CONTAINER_REGISTRY_NAME }}.azurecr.io" \
            --container-registry-user "${{ secrets.REGISTRY_USERNAME }}" \
            --container-registry-password "${{ secrets.REGISTRY_PASSWORD }}"

      - name: Run Health Check
        run: |
          echo "Waiting for deployment to be ready..."
          sleep 30
          curl -f https://ai-stock-tracker-prod-webapp.azurewebsites.net/health || exit 1
          echo "Health check passed!"

  security-scan:
    runs-on: ubuntu-latest
    needs: build
    name: Security Scan
    if: github.event_name == 'pull_request'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build.outputs.container-image }}
          format: "sarif"
          output: "trivy-results.sarif"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: "trivy-results.sarif"
