name: Generate Changelog

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Changelog Weaver
        run: |
          python -m pip install --upgrade pip
          # Install directly from the official repository
          python -m pip install git+https://github.com/Hankanman/Changelog-Weaver.git

      - name: Create .env file for Changelog Weaver
        run: |
          echo "SOLUTION_NAME=${{ github.repository }}" >> .env
          echo "RELEASE_VERSION=${{ github.ref_name }}" >> .env
          echo "SOFTWARE_SUMMARY=Release ${{ github.ref_name }}" >> .env
          echo "GET_ITEM_SUMMARY=True" >> .env
          echo "GET_CHANGELOG_SUMMARY=True" >> .env
          echo "PROJECT_URL=https://github.com/${{ github.repository }}" >> .env
          echo "QUERY=is:closed" >> .env
          echo "ACCESS_TOKEN=${{ secrets.SARIF_UPLOAD_TOKEN }}" >> .env

          # Use Azure OpenAI - set these repository secrets before running the workflow:
          # - AZURE_OPENAI_KEY (the API key)
          # - AZURE_OPENAI_ENDPOINT (e.g. https://my-openai-resource.openai.azure.com)
          # - AZURE_OPENAI_DEPLOYMENT_NAME (the deployment name for the model)
          echo "GPT_API_KEY=${{ secrets.AZURE_OPENAI_KEY }}" >> .env
          echo "MODEL_BASE_URL=${{ vars.AZURE_OPENAI_ENDPOINT }}" >> .env
          echo "MODEL=${{ vars.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> .env

          echo "OUTPUT_FOLDER=Releases" >> .env
          echo "LOG_LEVEL=INFO" >> .env

      - name: Generate Changelog
        run: python -m changelog_weaver

      - name: Upload Changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: Releases/*.md

      - name: Attach Changelog to Release
        uses: softprops/action-gh-release@v1
        with:
          files: Releases/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.SARIF_UPLOAD_TOKEN }}
