name: Generate Changelog

on:
  release:
    types: [created]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Changelog Weaver
        run: |
          git clone --depth 1 https://github.com/Hankanman/Changelog-Weaver.git changelog-weaver

      - name: Install Changelog Weaver dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r changelog-weaver/requirements.txt

      - name: Create .env file for Changelog Weaver
        run: |
          echo "SOLUTION_NAME=${{ github.repository }}" >> changelog-weaver/.env
          echo "RELEASE_VERSION=${{ github.ref_name }}" >> changelog-weaver/.env
          echo "SOFTWARE_SUMMARY=Release ${{ github.ref_name }}" >> changelog-weaver/.env
          echo "GET_ITEM_SUMMARY=True" >> changelog-weaver/.env
          echo "GET_CHANGELOG_SUMMARY=True" >> changelog-weaver/.env
          echo "PROJECT_URL=https://github.com/${{ github.repository }}" >> changelog-weaver/.env
          echo "QUERY=is:closed" >> changelog-weaver/.env
          echo "ACCESS_TOKEN=${{ secrets.GITHUB_TOKEN }}" >> changelog-weaver/.env

          # Use Azure OpenAI - set these repository secrets before running the workflow:
          # - AZURE_OPENAI_KEY (the API key)
          # - AZURE_OPENAI_ENDPOINT (e.g. https://my-openai-resource.openai.azure.com)
          # - AZURE_OPENAI_DEPLOYMENT_NAME (the deployment name for the model)
          echo "GPT_API_KEY=${{ secrets.AZURE_OPENAI_KEY }}" >> changelog-weaver/.env
          echo "MODEL_BASE_URL=${{ secrets.AZURE_OPENAI_ENDPOINT }}" >> changelog-weaver/.env
          echo "MODEL=${{ secrets.AZURE_OPENAI_DEPLOYMENT_NAME }}" >> changelog-weaver/.env

          echo "OUTPUT_FOLDER=Releases" >> changelog-weaver/.env
          echo "LOG_LEVEL=INFO" >> changelog-weaver/.env

      - name: Generate Changelog
        run: |
          cd changelog-weaver
          python -m changelog_weaver

      - name: Upload Changelog artifact
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: changelog-weaver/Releases/*.md

      - name: Attach Changelog to Release
        uses: softprops/action-gh-release@v1
        with:
          files: changelog-weaver/Releases/*.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
