name: Selenium UI Tests

on:
  push:
    paths:
      - 'AiStockTradeApp.SeleniumTests/**'
      - 'AiStockTradeApp/**'
      - 'scripts/run-selenium-tests.ps1'
      - '.github/workflows/selenium-tests.yml'
  pull_request:
    paths:
      - 'AiStockTradeApp.SeleniumTests/**'
      - 'AiStockTradeApp/**'
      - 'scripts/run-selenium-tests.ps1'
      - '.github/workflows/selenium-tests.yml'
  workflow_dispatch:
    inputs:
      filterType:
        description: 'Filter type (None|Category|AdoId)'
        required: false
        default: 'None'
        type: choice
        options: [None, Category, AdoId]
      filterValue:
        description: 'Filter value (e.g., Authenticated or 1403|1408)'
        required: false
        default: ''
        type: string
      culture:
        description: 'Culture (en|fr)'
        required: false
        default: 'en'
        type: string

jobs:
  selenium-tests:
    name: Selenium Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          include-prerelease: true

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1
        id: chrome

      - name: Display Chrome Info
        run: |
          echo "Chrome version: ${{ steps.chrome.outputs.chrome-version }}"
          echo "Chrome path: ${{ steps.chrome.outputs.chrome-path }}"

      - name: Determine Filter
        id: filter
        shell: pwsh
        run: |
          $type = '${{ github.event.inputs.filterType }}'
          $value = '${{ github.event.inputs.filterValue }}'
          $filter = ''
          if ($type -eq 'Category' -and $value) { $filter = "-Category $value" }
          elseif ($type -eq 'AdoId' -and $value) { $filter = "-AdoId $value" }
          else { $filter = '' }
          echo "filterArgs=$filter" >> $env:GITHUB_OUTPUT

      - name: Run Selenium Tests (single job)
        shell: pwsh
        env:
          SELENIUM_USERNAME: ${{ secrets.SELENIUM_USERNAME }}
          SELENIUM_PASSWORD: ${{ secrets.SELENIUM_PASSWORD }}
          DISABLE_SELENIUM_TEST_AUTOSTART: true
        run: |
          $cmd = "./scripts/run-selenium-tests.ps1 -CI -Configuration Release -EnableTests -Headless:`$true"
          if ('${{ github.event.inputs.culture }}') { $cmd += " -Culture ${{ github.event.inputs.culture }}" }
          $filter = '${{ steps.filter.outputs.filterArgs }}'
          if ($filter) { $cmd += " $filter" }
          if ($env:SELENIUM_USERNAME) { $cmd += " -Username `"$env:SELENIUM_USERNAME`"" }
          if ($env:SELENIUM_PASSWORD) { $cmd += " -Password `"$env:SELENIUM_PASSWORD`"" }
          Write-Host "Executing: $cmd"
          Invoke-Expression $cmd

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: selenium-trx
          path: |
            **/TestResults/**/*.trx
            AiStockTradeApp.SeleniumTests/TestResults/**/*.trx
